help ACIDVAR.M                    , pause
help BACKPRO1.M                   , pause
help BACKPRO2.M                   , pause
help BARNES.M                     , pause
help BETACF.M                     , pause
help BETAI.M                      , pause
help BFGSMIN.M                    , pause
help CA.M                         , pause
help CENTER.M                     , pause
help CLASSI.M                     , pause
help CODE.M                       , pause
help CODE2.M                      , pause
help COMPOSIT.M                   , pause
help CONSTRAI.M                   , pause
help CONTENTS.M                   , pause
help CONTRACT.M                   , pause
help CORRCOV.M                    , pause
help CROSBACK.M                   , pause
help CROSFORW.M                   , pause
help CROSPCRQ.M                   , pause
help CROSPLSQ.M                   , pause
help CROSPVAL.M                   , pause
help CROSREG.M                    , pause
help CSUM.M                       , pause
help DATJUL.M                     , pause
help DENSCHI.M                    , pause
help DENSF.M                      , pause
help DENSGAMM.M                   , pause
help DENSLOGN.M                   , pause
help DENST.M                      , pause
help DESISTEF.M                   , pause
help DISTCHI.M                    , pause
help DISTF.M                      , pause
help DISTN.M                      , pause
help DISTT.M                      , pause
help DOSELOG.M                    , pause
help EWMA.M                       , pause
help FACECENT.M                   , pause
help FACT.M                       , pause
help FROUND.M                     , pause
help FSIMU.M                      , pause
help GAUSSIAN.M                   , pause
help GRADPATH.M                   , pause
help HADAM.M                      , pause
help HELPLIST.M                   , pause
help IDISTCHI.M                   , pause
help IDISTN.M                     , pause
help INITLAY1.M                   , pause
help INITLAY2.M                   , pause
help INTEGRAT.M                   , pause
help INTERA.M                     , pause
help IRAND.M                      , pause
help IRIS.MAT                     , pause
help JACOB.M                      , pause
help JULDAT.M                     , pause
help KEYSORT.M                    , pause
help LACKOFIT.M                   , pause
help LININT.M                     , pause
help LINPROG.M                    , pause
help LOGISTIC.M                   , pause
help MAVERAGE.M                   , pause
help MEANS.M                      , pause
help MESHGEN.M                    , pause
help MGAUSS.M                     , pause
help MINUS.M                      , pause
help MPN0.M                       , pause
help MPNN.M                       , pause
help MTON.M                       , pause
help NIRDEMO.MAT                  , pause
help NORMSPEC.M                   , pause
help NORMVEC.M                    , pause
help OLD                          , pause
help ONEG.M                       , pause
help OSIMU.M                      , pause
help OVER.M                       , pause
help PCA.M                        , pause
help PCA2.M                       , pause
help PCR.M                        , pause
help PCREG.M                      , pause
help PCRPRED.M                    , pause
help PCRTEST.M                    , pause
help PICK.M                       , pause
help PLOTBI.M                     , pause
help PLOTCHI.M                    , pause
help PLOTCONT.M                   , pause
help PLOTDIM.M                    , pause
help PLOTF.M                      , pause
help PLOTMAT.M                    , pause
help PLOTN.M                      , pause
help PLOTNORM.M                   , pause
help PLOTPCA.M                    , pause
help PLOTQ.M                      , pause
help PLOTQUAD.M                   , pause
help PLOTT.M                      , pause
help PLS.M                        , pause
help PLSPRED.M                    , pause
help PLSREG.M                     , pause
help PLSTEST.M                    , pause
help POLRIB.M                     , pause
help POOL.M                       , pause
help PREDN1.M                     , pause
help PREDN2.M                     , pause
help PRODUCTS.M                   , pause
help QUADCANA.M                   , pause
help QUADCOMP.M                   , pause
help QUADEVAL.M                   , pause
help QUADGRAD.M                   , pause
help QUADMAT.M                    , pause
help R2.M                         , pause
help RANDNG.M                     , pause
help RANDOMIZ.M                   , pause
help RANDPERM.M                   , pause
help READFILE.M                   , pause
help README.TXT                   , pause
help REGBACK.M                    , pause
help REGPRED.M                    , pause
help REGRES.M                     , pause
help REGSTAT.M                    , pause
help REMOSAME.M                   , pause
help REMOVE.M                     , pause
help REPRES.M                     , pause
help RESNORM.M                    , pause
help RIDGEREG.M                   , pause
help SCALE.M                      , pause
help SCALEAB.M                    , pause
help SCREEN.M                     , pause
help SIGNICHI.M                   , pause
help SIGNIT.M                     , pause
help SIMFLEX.M                    , pause
help SIMPCENT.M                   , pause
help SIMPLAT.M                    , pause
help SMOOTHB.M                    , pause
help SORTCOL.M                    , pause
help SORTEIG.M                    , pause
help SORTKEY.M                    , pause
help SORTMAT.M                    , pause
help SORTROW.M                    , pause
help STRVEC.M                     , pause
help STRVECF.M                    , pause
help TAGUCHI.M                    , pause
help TTEST.M                      , pause
help TWON.M                       , pause
help UNION.M                      , pause
help UNSCALE.M                    , pause
help VARNAMES.M                   , pause
help VECTRIU.M                    , pause
help WRITETAB.M                   , pause
help ZEROG.M                      , pause
help ZERONEGA.M                   , pause
